[tool.poetry]
name = "poet"
version = "0.1.0"
description = "This is my cowsay project!"
authors = ["Julita Marshall <julitamcg5@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.6"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"
pylint = "^2.5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
